//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_bangiay_buoi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAN_PHAM
    {
        public int MaSP { get; set; }
        public string Ten_san_pham { get; set; }
        public string Anh { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<int> So_luong { get; set; }
        public Nullable<byte> Trang_thai { get; set; }
    }
}
